import {uniqueId} from 'lodash';
import {Dimensions, Platform, PixelRatio} from 'react-native';
import {Colors} from '@/styles/Colors';
import {FontSize} from '@/styles/Fonts';


const uId = uniqueId();
const screen = {
    pixel: 1 / PixelRatio.get(),
    ...Dimensions.get('screen'),
    isIOS: Platform.OS === 'ios',
};
export default {
    popupContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        justifyContent: 'center',
        alignItems: 'center',
        width: screen.width,
        height: screen.height,
        overflow: 'hidden',
        backgroundColor: 'rgba(00, 00, 00, 0)',
       
    },
    overlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: screen.width,
        height: screen.height,
        backgroundColor: '#000',
        opacity: .3,
    },
    tipBoxView: {
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
        width: screen.width - 25,
        borderRadius: 8,
        overflow: 'hidden',
    },
    tipBox: {
        paddingTop: 16,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    tipTitleBox: {
        paddingBottom: 8,
        marginTop: 5,
        textAlign: 'center',
        paddingHorizontal: 24,
        width: screen.width - 32,
        justifyContent: 'center',
        alignItems: 'center',
    },
    tipTitle: {
        fontSize: screen.isIOS ? 24 : 20,
        fontWeight: 'bold',
        textAlign: 'center',
        color: 'black',
    },
    tipContentBox: {
        marginLeft: 25,
        marginRight: 25,
        flexDirection: 'column',
        marginBottom: 16,
        // marginTop: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    tipContent: {
        fontSize: FontSize.Regular,
        margin: 5,
        marginTop: screen.isIOS ? 3 : 5,
        marginBottom: screen.isIOS ? 7 : 5,
        textAlign: 'center',
        color: 'black',
    },
    line: {
        height: screen.pixel,
        width: screen.width - 25,
        backgroundColor: '#ddd',
    },
    btnBox: {
        width: screen.width - 200,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        height: 50,
        borderRadius: 26,
        paddingHorizontal: 14,
        paddingBottom: 16,
        marginBottom: 5,
    },
    btnBoxMulti: {
        paddingHorizontal: 14,
        width: screen.width - 200,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        height: 50,
        borderRadius: 26,
        marginBottom: 16,
    },
    btnTextBox: {
        flexGrow: 1,
        // marginLeft: 10,
        marginHorizontal: 10,
        // marginRight: 10,
        marginBottom: 10,
        borderRadius: 26,
        height: 40,
        backgroundColor: Colors.light.redBase,
        justifyContent: 'center',
        alignItems: 'center',
    },
    btnTextBoxMulti: {
        flexGrow: 1,
        flexDirection: 'row',
        height: 40,
        borderRadius: 26,
        justifyContent: 'center',
        alignItems: 'center',
    },
    btnLineVertical: {
        height: 40,
        width: screen.pixel,
        backgroundColor: 'white',
    },
    btnLineHorizontal: {
        height: screen.pixel,
        width: '100%',
        backgroundColor: 'white',
    },
    btnText: {
        textAlign: 'center',
        fontWeight: 'bold',
        fontSize: FontSize.Regular,
        color: '#ffffff',
        fontStyle: 'normal',
    },
    btnTextTextBoxMulti: {
        flex: 1,
        textAlign: 'center',
        fontSize: FontSize.Regular,
        color: Colors.light.primary,
    },
    hidden: {
        position: 'absolute',
        height: 0,
        width: 0,
        top: 0,
        left: 0,
    },
};
